version: '3'
services: 

 mysql:
  image: mysql
  restart: always
  hostname: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=my-secret-pw
  volumes:
   - mysql:/var/lib/mysql/
   - ./conf/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql

 traccar:
  image: marcelmaatkamp/traccar-server
  hostname: traccar
  restart: always
  ports:
   - "5000-5150:5000-5150"
   - "8082:8082"
  volumes:
   - traccar-db:/opt/traccar/data/database
   - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml

  evolution-api:
    image: atendai/evolution-api
    command: ["node", "./dist/src/main.js"]
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - API_KEY=traccar-api_evolution2024
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances
volumes:
  traccar-db:
  mysql:
